language: python
python:
- '3.6'
install:
- pip install .
- pip install -r requirements.txt
env:
  global:
    authtoken:
      secure: 5GqmKCbVWRRPaYJ1iOzI5Vr1TqlnsUFV31dY5TGkQwGkOW4/zyie5uqRZqsUDCeeQl3fzgj68zA5wcW1EsUrOY2GPAR4zvcsClRDp5kn1fNI2pWV4cCpCFbztH0oTpt58Cy2pu+8vVdBaJ6l5dzKOCY99xaBqadh7f3ebhBpfTPopgGM4V4CqC8djMNlDOyaUXQ49gVunI64PNL+C12zac17caF1eYHE+p0j0Zgeu5WnHjBAA71mmzQLd9Zv7apTP3EqDFDIfGP8LM1EApXyEDkgvKVzhOUKSkuQ5kg0wpufcAsR29wFfkivzsR/RM7OP+J04Vd4LNRSzmE0G5fQq9LbZxw2N+1MaIo6hdNz6LJf4w4tnvG5ACCdHxKRt8k7+c02yQlJbTNCEb+E/fykeJR3l3s45xaDjdA+m3+BDanIMX2hYG0lJfq7OaiVft8tADoNQJ80erFfZ0WikhxFJGi70Km6B7DjUNuYwEaXNOXZPuopG581HKp5a9gQ5cJA4dIZYhogTjHkydb3JxZaZzQpdvRoWibzKmeKHkGl5apy4GE1R3VZP9142FM9dJkPPMdPWyI+2s5LkrQodIDaIz2FLZssK5VGuaX4vmbf4xHkUnRgNfsbedPhNLK2TwHR2TUqOiXLrzgHkrbpym5MN6kJupa1Y8MQdZwPsZJkB/A=
script: py.test
after_success:
- coveralls
